### ISSUE TITLE
Suggestions for different emoji

### ISSUE THREAD

**Issue by firasm** [ubc/emoji-feedback#10]
I'm starting to feel the thumbs up/ thumbs down emoji are a bit redundant and may just be confusing. 

If we stick to five, here are two other suggestions:

😁😀😐😕😞
😁😀😕😞😡

**Comment by justin0022** [comment]
We don't have to stick to 5 - I can make that configurable, although it may be a slight pain to implement

**Comment by firasm** [comment]
around 5 is good... 

Here are Github's 5:
![github](https://user-images.githubusercontent.com/2507459/50999796-0fb10500-14e0-11e9-87d0-79618aed17da.png)

I had the idea that the last one could be a *wildcard* and they could select their own, but I convinced myself against it. Will be way too complicated to interpret 

![selector](https://user-images.githubusercontent.com/2507459/50999930-6ae2f780-14e0-11e9-97ae-053584ae1d05.png)

**Comment by justin0022** [comment]
Okay. Github has 6, but I think 5 is fine then.

**Comment by justin0022** [comment]
I've made this easily configurable now on application init, so closing this issue.
