### ISSUE TITLE
Send the question text along with the emoji/comment requests

### ISSUE THREAD

**Issue by andrew-gardener** [ubc/emoji-feedback#31]

**Comment by justin0022** [comment]
Implemented here: https://github.com/ubc/emoji-feedback/commit/197dde74f7e74ce72828b2e86fd627fc370a6a71

**Comment by andrew-gardener** [comment]
wasn't added for comment feedback request

**Comment by justin0022** [comment]
Done for comment requests here: https://github.com/ubc/emoji-feedback/commit/35861e903cec4c8a6f5e72a3d35de01093b66048
