### ISSUE TITLE
Send the list of emojis in the emoji feedback request

### ISSUE THREAD

**Issue by andrew-gardener** [ubc/emoji-feedback#33]

**Comment by andrew-gardener** [comment]
Actually instead of doing #31, #32 and this we could just create the scale object and send that to the backend instead

**Comment by andrew-gardener** [comment]
https://raw.githack.com/andrew-gardener/caliper-spec/develop-profile/Feedback-cs323-more-scales/profiles/feedback/caliper-profile-feedback-v1p1.html#multiselectionscale

**Comment by justin0022** [comment]
I'll leave this open until we discuss with Firas next week, but it's pretty much finished: https://github.com/ubc/emoji-feedback/commit/8ffb309b37ae17b085eca716325c9b60615724fd
