### ISSUE TITLE
Change text of prompt

### ISSUE THREAD

**Issue by firasm** [ubc/emoji-feedback#9]
Instead of ```You can give us written feedback below if you'd like``` 

how about:

```Let us know if you have ideas for new features or improvements!```

**Comment by justin0022** [comment]
Can we add `below` to the end? 
As in `Let us know if you have ideas for new features or improvements!`

**Comment by justin0022** [comment]
Fixed: https://github.com/ubc/emoji-feedback/commit/0fb44d435ce19f0832e5c7d50b3f269d46b8a665
